name: deploy-api-docs

on:  
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      haxe-version:
        description: 'Haxe version to use'
        required: true
        default: 4.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ github.event.inputs.haxe-version }}
      - name: Setup
        run: haxelib install dox
      - name: Build documentation
        run: |
          cd api
          haxe api.hxml -xml build/api.xml -D doc-gen
          haxe dox.hxml
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: api/pages
